[package]
name = "crystalization"
version = "0.1.0"
authors = ["Jules Youngberg <julesdayoungberg@gmail.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
rand = "0.8.4"